/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type newGreeting = ContractEventLog<{
  greeting: string;
  sender: string;
  0: string;
  1: string;
}>;

export interface Greeter extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): Greeter;
  clone(): Greeter;
  methods: {
    greet(): NonPayableTransactionObject<string>;

    setGreeting(_greeting: string): NonPayableTransactionObject<void>;
  };
  events: {
    newGreeting(cb?: Callback<newGreeting>): EventEmitter;
    newGreeting(
      options?: EventOptions,
      cb?: Callback<newGreeting>
    ): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "newGreeting", cb: Callback<newGreeting>): void;
  once(
    event: "newGreeting",
    options: EventOptions,
    cb: Callback<newGreeting>
  ): void;
}
