/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface PriceAware extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): PriceAware;
  clone(): PriceAware;
  methods: {
    getMaxBlockTimestampDelay(): NonPayableTransactionObject<string>;

    getMaxDataTimestampDelay(): NonPayableTransactionObject<string>;

    isSignerAuthorized(
      _receviedSigner: string
    ): NonPayableTransactionObject<boolean>;

    isTimestampValid(
      _receivedTimestamp: number | string | BN
    ): NonPayableTransactionObject<boolean>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
